### ISSUE TITLE
Relicense to LGPLv3

### ISSUE THREAD

**Issue by latk** [latk/p5-Util-Underscore#9]
I'm currently preparing release v1.3.0, and would like to use this opportunity to relicense Util::Underscore, either to Perl's license or preferably to the LGPL v3.0. As it turns out, the GPL is awfully restrictive for libraries ;-)

@dolmen, you previously contributed a couple of valuable improvements to this repository. Do you agree to relicense your changes under the [GNU Lesser General Public License v3.0](https://www.gnu.org/licenses/lgpl.html)? Please drop me a comment.

**Comment by dolmen** [comment]
I would prefer the Perl license as it would give less headaches to potential users of your modules (just a different licence than most of the CPAN can be an issue).
But in fact, I'm not using your module, so I don't really care. So LGPL v3 or Perl 5 license or [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) (it explicitely mentions the license applied to contributions) would be ok.
